import json, requests, pytest

BASE_URL = "http://127.0.0.1:5000/api"
HEADERS = {"Content-Type": "application/json"}

def load_signup_cases():
    with open('signup.json',"r") as f:
        return json.load()


@pytest.mark.parametrize("case", load_signup_cases())
def test_cases_validation(case):
    response = requests.post(f"{BASE_URL}/signup", json=case["payload"], headers=HEADERS)
    assert response.status_code == case["expected_status"]


    if case["expected_error"]:
        assert response.json() ["error"] == case["expected_error"]
    else:
        assert response.json() ["message"] == "Registration successful!"


    # Another path: testing end to end workflow from Singup-login- fetch dashboard

    def test_user_dashboard():
        email ="autmo@gmail.com"
        password="Super123"

    #1. create user profile via Signup
    singup_payload = {
        "name": "Alex QA",
        "email": email,
        "password": password,
        "retype_password": password
    }
    signup_res = requests.post(f"{BASE_URL}/signup", json=signup_payload, headers=HEADERS)
    assert signup_res.status_code == 201

    #Authentication of user via Login
    login_payload = {"email": email, "password": password}
    login_res = requests.post(f"{BASE_URL}/login", json=login_payload, headers=HEADERS)
    assert login_res.status_code == 200


    # Extract the dynamic security session token generated by the server
    auth_token = login_res.json()["token"]

    #GET method: Fetch the dashboard for the inividual user
    authenticated_headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {auth_token}"
    }
    dashboard_res = requests.get(f"{BASE_URL}/dashboard/{email}", headers=authenticated_headers)


    # 4. Data Integrity Assertions: Verify the user sees THEIR custom info
    assert dashboard_res.status_code == 200
    dashboard_data = dashboard_res.json()
    
    assert dashboard_data["welcome_message"] == "Welcome back, Alex QA!"
    assert dashboard_data["department_role"] == "Premium Member"
    assert "account_balance" in dashboard_data

    



        
        
